# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "move",
    srcs = ["move.cc"],
    copts = [],
    deps = [],
)

cc_binary(
    name = "vector",
    srcs = ["vector.cc"],
    copts = [],
    deps = [],
)