cc_binary(
    name = "record_batch_yusha",
    srcs = ["record_batch_yusha.cc"],
    deps = [
    ],
    copts = [
        "-std=c++20"
    ],
)


cc_binary(
    name = "types_test",
    srcs = [
        "types.h",
        "types_test.cc",
        ],
    deps = [
    ],
    copts = [
        "-std=c++20"
    ],
)

cc_binary(
    name = "rb",
    srcs = [
        "types.h",
        "record_batch_yusha.cc",
        ],
    deps = [
    ],
    copts = [
        "-std=c++20"
    ],
)

cc_binary(
    name = "auction",
    srcs = [
        "auction.cc",
        ],
    deps = [
    ],
    copts = [
        "-std=c++20"
    ],
)