# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary


cc_binary(
    name = "substr_concat_words",
    srcs = ["substr_concat_words.cc"],
    deps = [
    ],
    copts = [
        "-std=c++20"
    ],
)