
cc_library(
    name = "libRingBuffer",
    hdrs = ["ring_buffer.h"],
    srcs = [],
    deps = [
    ],
    copts = [
        "-std=c++20"
    ],
)

cc_binary(
    name = "rb",
    srcs = ["ring_buffer.cc"],
    deps = [
    ],
    copts = [
        "-std=c++20"
    ],
)
